---
output: 
   html_document:
     theme: null
     highlight: null
     mathjax: null
     css: margin_css.css
---

 
```{r,echo=F,message=F,warning=F,include=F, cache=T}

require(rgdal)
require(rgeos)
require(rmapshaper)
require(leaflet)
require(dplyr)

#setwd("//shestorfs01/Childrens Commissioner/2. Evidence Team/1. Live Projects/MH Briefing/MH Briefing 2020/R")

map <- readOGR(dsn = ".",layer="Clinical_Commissioning_Groups__April_2019__Boundaries_EN_BGC")
map <- rmapshaper :: ms_simplify(map,keep=0.1)


#saveRDS save any object in R in many formats

#saveRDS(map,"//shestorfs01/Childrens Commissioner/2. Evidence Team/1. Live Projects/MH Briefing/MH Briefing 2020/R/ccgmap19.rds")

#map <- readRDS("//shestorfs01/Childrens Commissioner/2. Evidence Team/1. Live Projects/MH Briefing/MH Briefing 2020/R/ccgmap19.rds")

map$CCG19CD <- as.character(map$CCG19CD)

ccg_code <- map@data %>% select(CCG19NM, CCG19CD)

mhdata20 <- read.csv("//shestorfs01/Childrens Commissioner/2. Evidence Team/1. Live Projects/MH Briefing/MH Briefing 2020/R/MH R tables 2020.csv", stringsAsFactors = F)

overall_sc <- mhdata20

london <- read.csv("//shestorfs01/Childrens Commissioner/2. Evidence Team/1. Live Projects/MH Briefing/MH Briefing 2020/R/london ccg.csv", stringsAsFactors = F)


# check that codes are in both datasets
overall_sc$ccg_cd[!overall_sc$ccg_cd %in% map$CCG19CD]

for(i in c("perc_budget","spend_YP","perc_access","avg_wait","perc_closed","overall_score")){
  
  if(!grepl("spend",i)){
  
  vNm<-rlang::sym(paste0(i,"_fill"))
  v1<-rlang::sym(i)
  
  overall_sc<-overall_sc %>%
    mutate(!!vNm:=scales::rescale(!!v1,c(0,1)))
  
  }else{
      
      vNm<-rlang::sym(paste0(i,"_fill"))
  v1<-rlang::sym(i)
  
  overall_sc<-overall_sc %>%
    mutate(!!vNm:=factor(ifelse(spend_YP< 40, "£20 to £40", 
                            ifelse(spend_YP< 60,"£40 to 60", 
                              ifelse(spend_YP< 80,"£60 to £80",
                                ifelse(spend_YP< 100,"£80 to £100","£100+")))),
      levels=c("£20 to £40","£40 to 60","£60 to £80","£80 to £100","£100+"))) 

      
    }
  
  
}

# change from British standard to GPS format 
map <- spTransform(map, "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")

map <- sp::merge(map,overall_sc, by.x="CCG19CD", by.y="ccg_cd")

outcomes<-data.frame(var=c("perc_budget","spend_YP","perc_access","avg_wait","perc_closed","overall_score"),
                     lb=c("% of CCG budget spent on CAMHS","Spend per child (£) on CAMHS","% of children referred to CAMHS",
                          "Average waiting time (days)","% of CAMHS referrals closed before treatment","CCG overall score"),stringsAsFactors = F)

require(ggplot2)
require(RColorBrewer)

pal <- colorNumeric("viridis", domain = c(0,1))
pal_bin<-colorFactor("viridis", domain = overall_sc$spend_YP_fill,ordered = T)

labels <- lapply(list("perc_budget","spend_YP","perc_access","avg_wait","perc_closed","overall_score"), 
                 function(x){
                   
                   if(grepl("perc",x)){
                     paste0("<strong>", map$CCG19NM, "</strong><br/>", outcomes$lb[outcomes$var==x],": ",
                            round(map@data[,x],4)*100)
                     
                   }else{
                     paste0("<strong>", map$CCG19NM, "</strong><br/>", outcomes$lb[outcomes$var==x],": ",
                            round(map@data[,x]))
                     
                   }
                   
                            
                   })

for(i in seq_len(length(labels))){
  
  labels[[i]]<-lapply(labels[[i]],htmltools::HTML)
  
}

names(labels)<-c("perc_budget","spend_YP","perc_access","avg_wait","perc_closed","overall_score")
    

```

```{r, out.width="100%",echo=F,message=F,warning=F}
                                                                                       
leaflet(data=map, options = leafletOptions(background="#FFF")) %>%
  addProviderTiles(providers$CartoDB) %>%
  addPolygons(color="#444444", weight=1, smoothFactor = 0.5,
              opacity=1.0, fillOpacity = 0.7, fillColor = ~pal(overall_score_fill),
              popupOptions = highlightOptions(bringToFront = T, weight=4),
              label =labels[["overall_score"]],group="CCG overall score") %>%
  
  addPolygons(color="#444444", weight=1, smoothFactor = 0.5,
              opacity=1.0, fillOpacity = 0.7, fillColor = ~pal(perc_closed_fill),
              popupOptions = highlightOptions(bringToFront = T, weight=4),
              label =labels[["perc_closed"]],group="% Referrals closed") %>%
  
  addPolygons(color="#444444", weight=1, smoothFactor = 0.5,
              opacity=1.0, fillOpacity = 0.7, fillColor = ~pal(avg_wait_fill),
              popupOptions = highlightOptions(bringToFront = T, weight=4),
              label =labels[["avg_wait"]],group="Average wait (days)") %>%
  
  addPolygons(color="#444444", weight=1, smoothFactor = 0.5,
              opacity=1.0, fillOpacity = 0.7, fillColor = ~pal(perc_access_fill),
              popupOptions = highlightOptions(bringToFront = T, weight=4),
              label =labels[["perc_access"]],group="% Referred to CAMHS") %>%
  
  addPolygons(color="#444444", weight=1, smoothFactor = 0.5,
              opacity=1.0, fillOpacity = 0.7, fillColor = ~pal_bin(spend_YP_fill),
              popupOptions = highlightOptions(bringToFront = T, weight=4),
              label =labels[["spend_YP"]],group="CAMHS spend per child") %>%
  
  addPolygons(color="#444444", weight=1, smoothFactor = 0.5,
              opacity=1.0, fillOpacity = 0.7, fillColor = ~pal(perc_budget_fill),
              popupOptions = highlightOptions(bringToFront = T, weight=4),
              label =labels[["perc_budget"]],group="% CCG budget spent on CAMHS") %>%
  
  addLayersControl(
    baseGroups = c("CCG overall score","% Referrals closed","Average wait (days)","% Referred to CAMHS","CAMHS spend per child","% CCG budget spent on CAMHS"),
    options = layersControlOptions(collapsed = FALSE)) %>%
  addLegend("topleft", pal = pal, values = seq(0,1),bins=5,
            labFormat = function(type, cuts, p) { 
              n = length(cuts) 
              cuts[n] = "Highest rate" 
              for (i in 2:(n-1)){cuts[i] = " "} 
              cuts[1] = "Lowest rate" 
              paste0(cuts[-n], cuts[-1])},
            title = "Title",
            na.label = "Missing/excluded",
            opacity = 0.7
  ) %>%
  addLegend("topleft", pal = pal_bin, values=factor(c("£20 to £40","£40 to 60","£60 to £80","£80 to £100","£100+"),levels = c("£20 to £40","£40 to 60","£60 to £80","£80 to £100","£100+")),
            title = "Title",
            na.label = "Missing/excluded",
            opacity = 0.7
  )

```

```{r, results='asis',echo=F,warning=F}
minVals<-sapply(c("overall_score","perc_closed","avg_wait","perc_access","spend_YP","perc_budget"),function(x){
     
  if(grepl("perc",x)){
  
     paste0(round(min(overall_sc[,x])*100,1),"%")
    }else if(x=="avg_wait"){
       
      paste0(min(overall_sc[,x]))
       
    }else if(x=="spend_YP"){
       paste0("£",min(overall_sc[,x]))
    }else{
       
      paste0(min(overall_sc[,x]))
     }
     
   }) 

maxVals<-sapply(c("overall_score","perc_closed","avg_wait","perc_access","spend_YP","perc_budget"),function(x){
     
  if(grepl("perc",x)){
  
     paste0(round(max(overall_sc[,x])*100,1),"%")
    }else if(x=="avg_wait"){
       
      paste0(max(overall_sc[,x]))
       
    }else if(x=="spend_YP"){
       paste0("£",max(overall_sc[,x]))
    }else{
       
      paste0(max(overall_sc[,x]))
     }
   }) 

varVals<-c("CCG overall score</br>Lower = worse","% of referrals closed</br>without treatment","Average CYPMHS waiting time (days)","% of children referred to CYPMHS","CYPMHS spend per child","% of CCG budget</br>spent on CYPMHS")

minVals<-jsonlite::toJSON(minVals,"values")

maxVals<-jsonlite::toJSON(maxVals,"values")

varVals<-jsonlite::toJSON(varVals,"values")

cat(paste0('<script>
  
  window.addEventListener("load", function () {
    var eles = document.getElementsByClassName("leaflet-control-layers-base");
    
    eles[0].insertAdjacentHTML("afterbegin","<span style=',"'","margin-bottom:3px;font-weight:bold","'",'>Select measure to view:</span>")



  var maxArr = ',maxVals,';

  var minArr = ',minVals,';

  var varArr = ',varVals,';

  var legendEntries = document.getElementsByClassName("leaflet-control-layers-selector")

  for (var i=0; i < legendEntries.length; i++){

  legendEntries[i].setAttribute("minval_map",minArr[i])

  legendEntries[i].setAttribute("maxval_map",maxArr[i])

  legendEntries[i].setAttribute("varval_map",varArr[i])

  }

var legend_1 = document.getElementsByClassName("info legend leaflet-control")[0]

  var legEntries_1 = legend_1.getElementsByTagName("text")

  legEntries_1[0].innerHTML = minArr[0]

  legEntries_1[0].setAttribute("dx",50)

  legEntries_1[legEntries_1.length - 1].innerHTML = maxArr[0]

  legEntries_1[legEntries_1.length - 1].setAttribute("dx",50)

  var legendTitle_1 = legend_1.getElementsByTagName("strong")

  legendTitle_1[0].innerHTML = varArr[0]

  var legend_2 = document.getElementsByClassName("info legend leaflet-control")[1]

  legend_2.style.display = "none"

f3 = function(){

  var minVal_var = this.getAttribute("minval_map")

  var maxVal_var = this.getAttribute("maxval_map")

  var varval_var = this.getAttribute("varval_map")

  if(varval_var != "CYPMHS spend per child") {

  var legend_2 = document.getElementsByClassName("info legend leaflet-control")[1]

  legend_2.style.display = "none"
  
  var legend = document.getElementsByClassName("info legend leaflet-control")[0]

 legend.style.display = "initial"

  var legendTitle = legend.getElementsByTagName("strong")

  legendTitle[0].innerHTML = varval_var

  var legEntries = legend.getElementsByTagName("text")

  legEntries[0].innerHTML = minVal_var

  legEntries[0].setAttribute("dx",50)

  legEntries[legEntries.length - 1].innerHTML = maxVal_var

  legEntries[legEntries.length - 1].setAttribute("dx",50)


  } else{
  
  var legend_2 = document.getElementsByClassName("info legend leaflet-control")[0]

  legend_2.style.display = "none"
  
  var legend = document.getElementsByClassName("info legend leaflet-control")[1]

  legend.style.display = "initial"

  var legendTitle = legend.getElementsByTagName("strong")

  legendTitle[0].innerHTML = varval_var


  }

  }

  for (var i=0; i < legendEntries.length; i++){

  legendEntries[i].addEventListener("click",f3)

  }
    
})

  
  

  </script>'
  ))
```



<br/> <br/>

